In [12]:
import numpy as np
import pandas as pd
import math

In [13]:
ground = pd.read_csv('C:/Users/ductm/Downloads/ground_truth_2024_06_08_13_26.csv')
ground_truth = pd.DataFrame()
ground_truth['utcTimeMillis'] = ground['utcTimeMillis'] - 1000
ground_truth['Latitude'] = ground['Latitude']
ground_truth['Longitude'] = ground['Longitude']
position = pd.read_csv('C:/Users/ductm/Downloads/position_data_2024_06_08_13_26_sat1.csv')
merged_df = pd.merge(ground_truth, position, how = 'inner', on='utcTimeMillis', suffixes=('_1', '_2'))
merged_df = merged_df.dropna()
merged_df

,utcTimeMillis,Latitude_1,Longitude_1,WKT,Latitude_2,Longitude_2
0,1.717828e+12,21.005127,105.844707,POINT (105.84455899341987 21.00570169871385),21.005702,105.844559
1,1.717828e+12,21.005112,105.844708,POINT (105.84451837004522 21.005646653179987),21.005647,105.844518
2,1.717828e+12,21.005078,105.844723,POINT (105.84450801609141 21.005637523383665),21.005638,105.844508
3,1.717828e+12,21.005047,105.844738,POINT (105.84451087330875 21.005634618202127),21.005635,105.844511
4,1.717828e+12,21.005020,105.844755,POINT (105.84451869454176 21.005608676873695),21.005609,105.844519
...,...,...,...,...,...,...
260,1.717828e+12,21.005667,105.845677,POINT (105.84561928220434 21.005511738584897),21.005512,105.845619
261,1.717828e+12,21.005608,105.845678,POINT (105.84556488514922 21.005487782143405),21.005488,105.845565
262,1.717828e+12,21.005553,105.845677,POINT (105.84560896462683 21.005266416825854),21.005266,105.845609
263,1.717828e+12,21.005500,105.845672,POINT (105.84560205586776 21.00521580053529),21.005216,105.845602
264,1.717828e+12,21.005450,105.845673,POINT (105.8454670087941 21.005284360396697),21.005284,105.845467

In [14]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0  # Bán kính Trái Đất trung bình bằng km
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)
    
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    
    distance = R * c * 1000
    return distance

In [22]:
merged_df['Distance'] = merged_df.apply(lambda row: haversine(row['Latitude_1'], row['Longitude_1'], row['Latitude_2'], row['Longitude_2']), axis=1)
merged_df.to_csv('distance.csv')
mean_distance = np.sqrt(np.square(merged_df['Distance']).mean())
mean_distance

22.86639980873598